name: yamstack
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0

  get: ^4.3.6
  dio: ^4.0.0
  retrofit: any
  json_annotation: ^4.1.0
  shared_preferences: ^2.0.7
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito: ^5.0.15
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
  retrofit_generator: any
  lint: ^1.6.0
  logger: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/
