// Mocks generated by Mockito 5.0.15 from annotations
// in yamstack/test/unit-tests/src/data/source/remote/api/user/user_api_join_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yamstack/src/data/source/remote/dio_client.dart' as _i3;
import 'package:yamstack/src/data/source/remote/response/base_single_response.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeBaseSingleResponse_0<T> extends _i1.Fake
    implements _i2.BaseSingleResponse<T> {}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i3.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseSingleResponse<T>> getSingleResponse<T>(String? url,
          {Map<String, dynamic>? request}) =>
      (super.noSuchMethod(
              Invocation.method(#getSingleResponse, [url], {#request: request}),
              returnValue: Future<_i2.BaseSingleResponse<T>>.value(
                  _FakeBaseSingleResponse_0<T>()))
          as _i4.Future<_i2.BaseSingleResponse<T>>);
  @override
  _i4.Future<_i2.BaseSingleResponse<T>> postSingleResponse<T>(
          String? url, Map<String, dynamic>? request) =>
      (super.noSuchMethod(
              Invocation.method(#postSingleResponse, [url, request]),
              returnValue: Future<_i2.BaseSingleResponse<T>>.value(
                  _FakeBaseSingleResponse_0<T>()))
          as _i4.Future<_i2.BaseSingleResponse<T>>);
  @override
  String toString() => super.toString();
}
